Add Support for HRI Features
auth0/go-auth0 pull request #429
Opened 2024-08-06 11:26 UTC by developerkunal

### 🔧 Changes
- Add Support for HRI Features

### 📚 References

### 🔬 Testing

### 📝 Checklist

- [x] All new/changed/fixed functionality is covered by tests (or N/A)
- [x] I have added documentation for all new/changed functionality (or N/A)

2024-08-07 06:41 UTC, gyaneshgouraw-okta approved these changes

2024-08-07 06:45 UTC, gyaneshgouraw-okta commented
Lets add a bit more detail to PR description. We should add 

- Add detail/link which has some description about HRI
- We can document management api corresponding docs link
- Any other relevant doc which can assist users

2024-08-09 13:53 UTC, acwest commented on management/tenant_test.go
> +		AcrValuesSupported:                   &[]string{"foo", "bar"},
we need tests for both setting this to null in the api, and omitting it in the API

2024-08-09 13:55 UTC, acwest requested changes
more testing of new values, particularly `AcrValuesSupported`

2024-08-13 13:30 UTC, acwest approved these changes

2024-08-13 13:44 UTC, merged