Organizations for Client Credentials
auth0/go-auth0 pull request #432
Opened 2024-08-13 09:30 UTC by duedares-rvj

### 🔧 Changes
1. Added default_organization to GET/POST/PATCH /api/v2/clients/{id}
2. Support query param ```identifiers``` for GET /api/v2/organizations/{org_id}/client-grants
3. Support query param ```grant_ids``` for GET /api/v2/resource-servers
4. Support query param ```q``` for GET /api/v2/clients

### 📚 References

### 🔬 Testing
Added tests to query using the query string and validated the response.

### 📝 Checklist

- [ ] All new/changed/fixed functionality is covered by tests (or N/A)
- [ ] I have added documentation for all new/changed functionality (or N/A)

2024-08-20 14:18 UTC, acwest submitted a review, later dismissed

2024-08-21 14:21 UTC, acwest submitted a review, later dismissed

2024-08-22 06:59 UTC, developerkunal commented on management/client.go
> +	DefaultOrganization *ClientDefaultOrganization `json:"default_organization,omitempty"`
We have to add a test case for testing this in `client_test.go`  because this relates to the Client Manager.

2024-08-22 07:00 UTC, developerkunal requested changes

2024-08-22 07:00 UTC, developerkunal commented on management/client.go
> +	DefaultOrganization *ClientDefaultOrganization `json:"default_organization,omitempty"`
We have to add a test case for testing this in client_test.go because this relates to the Client Manager.

2024-08-26 15:19 UTC, developerkunal approved these changes
LGTM

2024-08-26 15:19 UTC, merged