[2/2] DXCDT-129: Add vcr recordings for tests
auth0/go-auth0 pull request #68
Opened 2022-06-06 14:05 UTC by sergiughf

## Description

This PR adds the recordings for our go-vcr tests. 

Note: It does not yet enable the CI tests to use them. This will be done in the next PR. 

## References

## Testing

- [x] This change adds test coverage for new/changed/fixed functionality

## Checklist

- [x] I have read and agreed to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [x] I have read the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have reviewed my own code beforehand.
- [x] I have added documentation for new/changed functionality in this PR.
- [x] All active GitHub checks for tests, formatting, and security are passing.
- [x] The correct base branch is being used, if not `main`.

2022-06-06 16:26 UTC, evansims approved these changes
LGTM; is the failing test expected at this point?

2022-06-06 17:23 UTC, willvedd approved these changes
Thanks for breaking this out into it's own PR. Good work!

2022-06-07 01:11 UTC, Widcket commented on management/testdata/recordings/TestConnectionManager_Create/It_can_successfully_create_a_SAML_Connection.yaml
> +      {"name":"Test-SAML-Connection-1654521050","strategy":"samlp","options":{"signingCert":"-----BEGIN CERTIFICATE-----\nMIID6TCCA1ICAQEwDQYJKoZIhvcNAQEFBQAwgYsxCzAJBgNVBAYTAlVTMRMwEQYD\nVQQIEwpDYWx
Should this be redacted as well?

2022-06-07 01:14 UTC, Widcket commented on management/testdata/recordings/TestConnectionManager_Read/It_can_successfully_read_a_SAML_Connection.yaml
> +      {"name":"Test-SAML-Connection-1654521050","strategy":"samlp","options":{"signingCert":"-----BEGIN CERTIFICATE-----\nMIID6TCCA1ICAQEwDQYJKoZIhvcNAQEFBQAwgYsxCzAJBgNVBAYTAlVTMRMwEQYD\nVQQIEwpDYWx
Should this be redacted as well?

2022-06-07 01:14 UTC, Widcket commented on management/testdata/recordings/TestConnectionManager_Read/It_can_successfully_read_a_SAML_Connection.yaml
> +    body: '{"id":"con_LexaQwCc0JZCJhHT","options":{"signingCert":"-----BEGIN CERTIFICATE-----\nMIID6TCCA1ICAQEwDQYJKoZIhvcNAQEFBQAwgYsxCzAJBgNVBAYTAlVTMRMwEQYD\nVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW
Same as above.

2022-06-07 01:15 UTC, Widcket commented on management/testdata/recordings/TestConnectionManager_Read/It_can_successfully_read_a_SAML_Connection.yaml
> +      CERTIFICATE-----\nMIID6TCCA1ICAQEwDQYJKoZIhvcNAQEFBQAwgYsxCzAJBgNVBAYTAlVTMRMwEQYD\nVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRQwEgYDVQQK\nEwtHb29nbGUgSW5jLjEMMAoGA1UECxMDRW5nMQwwCgY
Same as above.

2022-06-07 01:15 UTC, Widcket commented on management/testdata/recordings/TestConnectionManager_Read/It_can_successfully_read_a_SAML_Connection.yaml
> +    body: '{"id":"con_LexaQwCc0JZCJhHT","options":{"cert":"-----BEGIN CERTIFICATE-----\nMIID6TCCA1ICAQEwDQYJKoZIhvcNAQEFBQAwgYsxCzAJBgNVBAYTAlVTMRMwEQYD\nVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhb
Same as above.

2022-06-07 01:15 UTC, Widcket commented on management/testdata/recordings/TestConnectionManager_Read/It_can_successfully_read_a_SAML_Connection.yaml
> +      CERTIFICATE-----\nMIID6TCCA1ICAQEwDQYJKoZIhvcNAQEFBQAwgYsxCzAJBgNVBAYTAlVTMRMwEQYD\nVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRQwEgYDVQQK\nEwtHb29nbGUgSW5jLjEMMAoGA1UECxMDRW5nMQwwCgY
Same as above.

2022-06-07 01:55 UTC, Widcket requested changes
Left some comments about what appears to be some certs, not sure if it's relevant.

2022-06-07 12:19 UTC, Widcket approved these changes

2022-06-07 12:46 UTC, merged